on: push
jobs:
  drata-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Drata Action
        uses: drata/compliance-as-code-action@v1.0.0
        env:
            DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
            GITHUB_REPOSITORY: $GITHUB_REPOSITORY
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            minimumSeverity: 'CRITICAL'
